import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box, Container, CssBaseline, Link, Stack } from "@mui/material";
import Header from "./components/common/header";
import Footer from "./components/common/footer";
import { ThemeRegistry } from './ThemeProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <ThemeRegistry>
        <Stack minHeight={"100vh"}>
            <Header/> 
            <Box component={"main"} flexGrow={1}>
              {children}  
            </Box>
            <Footer/>
        </Stack>
      </ThemeRegistry>
    </body>
  </html>
  );
}
